part of './extentions.dart';

extension ThemeDataEx on ThemeData {
  ThemeData fromThemeDataTo(ThemeData? themeData) {
    return copyWith(
      applyElevationOverlayColor: themeData?.applyElevationOverlayColor,
      cupertinoOverrideTheme: themeData?.cupertinoOverrideTheme,
      extensions: themeData?.extensions.values,
      inputDecorationTheme: themeData?.inputDecorationTheme,
      materialTapTargetSize: themeData?.materialTapTargetSize,
      pageTransitionsTheme: themeData?.pageTransitionsTheme,
      platform: themeData?.platform,
      scrollbarTheme: themeData?.scrollbarTheme,
      splashFactory: themeData?.splashFactory,
      visualDensity: themeData?.visualDensity,
      // useMaterial3:themeData.useMaterial3 ,
      // colorScheme: themeData?.colorScheme,
      // brightness: themeData?.brightness,
      // primaryColor: themeData?.primaryColor,
      // textTheme: themeData?.textTheme,
      primaryColorLight: themeData?.primaryColorLight,
      primaryColorDark: themeData?.primaryColorDark,
      focusColor: themeData?.focusColor,
      hoverColor: themeData?.hoverColor,
      shadowColor: themeData?.shadowColor,
      canvasColor: themeData?.canvasColor,
      // scaffoldBackgroundColor:  themeData?.scaffoldBackgroundColor,
      // bottomAppBarColor: themeData?.bottomAppBarColor,
      cardColor: themeData?.cardColor,
      dividerColor: themeData?.dividerColor,
      highlightColor: themeData?.highlightColor,
      splashColor: themeData?.splashColor,
      // selectedRowColor: themeData?.selectedRowColor,
      unselectedWidgetColor: themeData?.unselectedWidgetColor,
      disabledColor: themeData?.disabledColor,
      secondaryHeaderColor: themeData?.secondaryHeaderColor,
      // backgroundColor: themeData?.backgroundColor,
      dialogBackgroundColor: themeData?.dialogBackgroundColor,
      indicatorColor: themeData?.indicatorColor,
      hintColor: themeData?.hintColor,
      // errorColor: themeData?.errorColor,
      // toggleableActiveColor: themeData?.toggleableActiveColor,
      typography: themeData?.typography,
      // textTheme: themeData?.textTheme,
      primaryTextTheme: themeData?.primaryTextTheme,
      iconTheme: themeData?.iconTheme,
      primaryIconTheme: themeData?.primaryIconTheme,
      appBarTheme: themeData?.appBarTheme,
      bannerTheme: themeData?.bannerTheme,
      bottomAppBarTheme: themeData?.bottomAppBarTheme,
      bottomNavigationBarTheme: themeData?.bottomNavigationBarTheme,
      bottomSheetTheme: themeData?.bottomSheetTheme,
      buttonBarTheme: themeData?.buttonBarTheme,
      buttonTheme: themeData?.buttonTheme,
      cardTheme: themeData?.cardTheme,
      checkboxTheme: themeData?.checkboxTheme,
      chipTheme: themeData?.chipTheme,
      dataTableTheme: themeData?.dataTableTheme,
      dialogTheme: themeData?.dialogTheme,
      dividerTheme: themeData?.dividerTheme,
      drawerTheme: themeData?.drawerTheme,
      elevatedButtonTheme: themeData?.elevatedButtonTheme,
      floatingActionButtonTheme: themeData?.floatingActionButtonTheme,
      listTileTheme: themeData?.listTileTheme,
      navigationBarTheme: themeData?.navigationBarTheme,
      navigationRailTheme: themeData?.navigationRailTheme,
      outlinedButtonTheme: themeData?.outlinedButtonTheme,
      popupMenuTheme: themeData?.popupMenuTheme,
      progressIndicatorTheme: themeData?.progressIndicatorTheme,
      radioTheme: themeData?.radioTheme,
      sliderTheme: themeData?.sliderTheme,
      snackBarTheme: themeData?.snackBarTheme,
      switchTheme: themeData?.switchTheme,
      tabBarTheme: themeData?.tabBarTheme,
      textButtonTheme: themeData?.textButtonTheme,
      textSelectionTheme: themeData?.textSelectionTheme,
      timePickerTheme: themeData?.timePickerTheme,
      toggleButtonsTheme: themeData?.toggleButtonsTheme,
      tooltipTheme: themeData?.tooltipTheme,
      expansionTileTheme: themeData?.expansionTileTheme,
    );
  }
}
